; ============================================================
; Pomodoro CYD — ESP32-2432S028R (Cheap Yellow Display 2.8")
; LVGL 9 via esp32_smartdisplay + Improv Wi-Fi + portail web
; ============================================================

[platformio]
default_envs = esp32-2432S028R

[env]
platform = espressif32@^6.9.0
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder
board_build.partitions = huge_app.csv

build_flags =
    -Ofast
    '-D BOARD_NAME="${this.board}"'
    '-D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_NONE'
    ; --- Config LVGL par flags (remplace lv_conf.h) ---
    -D LV_CONF_SKIP
    -D LV_COLOR_DEPTH=16
    -D LV_MEM_SIZE=49152U
    -D LV_USE_LOG=0
    -D LV_FONT_MONTSERRAT_12=1
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_16=1
    -D LV_FONT_MONTSERRAT_20=1
    -D LV_FONT_MONTSERRAT_24=1
    -D LV_FONT_MONTSERRAT_48=1
    ; --- Infos firmware (Improv / flasher) ---
    '-D FIRMWARE_NAME="Pomodoro CYD"'
    '-D FIRMWARE_VERSION="1.0.0"'

lib_deps =
    rzeldent/esp32_smartdisplay@^2.1.0

[env:esp32-2432S028R]
board = esp32-2432S028R

[env:esp32-2432S028Rv2]
board = esp32-2432S028Rv2

[env:esp32-2432S028Rv3]
board = esp32-2432S028Rv3
